### ISSUE TITLE
Waiting time formula

### ISSUE THREAD

**Issue by zsfelfoldi** [datahop/p2p-service-discovery#12]
I've been thinking about the new waiting time formula and I think it's definitely a good direction to have such a simple formula using the number of entries with the same IP/topic. I am not so sure about the ID, I don't think it avoids any possible attack (an attacker can very easily use many IDs). Actually if we are storing ENRs then probably each node ID has a single most recent ENR to advertise (potentially under multiple topics). It would be weird if we penalized advertising the same ENR under multiple topics more than creating different keys and ENRs for each topic (which would be a bad practice probably).
On the other hand, I would add a factor based on the total number of entries. This factor could converge to infinity as the total number approaches the global limit. Something like `1e-6 / (1-totalEntries/totalLimit)^10` (the exponent of 10 is just a guess but probably such a high exponent is desirable). This would simplify the design because you wouldn't need to separately handle the case where there is no more space in the table because it is guaranteed by the waiting time formula that it won't happen. It also provides more graceful breakdown properties. With the current design it seems risky to me that in some cases the IP/ID/topic factors might not be enough to keep the total number of regs low and many nodes will have these "golden tickets" with far enough cumulative waiting time and still all of them would be told to come back shortly (because the table is full) and all of them would come back frequently, causing excessive traffic. Maybe it's better to always use the waiting time to throttle traffic and drive the time up when the table is almost full. This would be something probably worth trying in the simulations.

**Comment by harnen** [comment]
Thank for the comments. I agree that IDs are cheap to generate. However, they still require some resources from an attacker (e.g., CPU to maintain multiple encrypted connections). It's not a solid line of defence, but it's something. 

Advertising multiple topics under the same UD shouldn't be a problem because of our routing strategy. I.e., one registrant will use different set of registrar for each topic it registers for. Thus, it shouldn't really happen that advertisements from a single honest ID end up at the same registrar. In any case, we'll run some tests to confirm that for different network sizes. 

Using the total occupancy in the formula sounds like a really good idea. We actually used it in the early designed, but then replaced with IP/topic/ID specific modifiers. I agree that it should handle much better cases where the table is almost full. I'll simulate that and post some results soon.

**Comment by harnen** [comment]
We recently revised the formula to the following:
**n** - capacity of the table
**d** - number of entries currently in the table
**d(IP)** - number of entries currently in the table with given IP
**d(ID)** - number of entries currently in the table with given ID
**d(topic)** - number of entries currently in the table with given topic
**a** - registration lifetime (time spent in the table)
**w** - waiting time
<img src="https://render.githubusercontent.com/render/math?math=\Large w=sum((\frac{1}{10^6}),(\frac{d(IP)}{d})^0.1,(\frac{d(ID)}{d})^0.1,(\frac{d(topic)}{d})^5) \frac{10a}{(1-\frac{n}{d})^10}">

The first part of the table promotes diversity, while the second part ensures that we'll not overflow and yields increasing waiting times as the table fills up. We used different exponents in for IDs/IPs and topics, as we expect a zipf topic distribution that we shouldn't discriminate against. This works pretty well.  The only problem seems to be that the formula doesn't keep Sybil requests out if the total number of registrations is much lower than the capacity of the table. In such a case, everyone will get really low waiting times regardless of the similarity scores. This is ok to some extent, but makes choosing the table size a crucial parameter for robustness which I'm not happy with. Especially that the number of requests can vary over time.

**Comment by harnen** [comment]
It seems that we find an optimal formula and determine a set of parameters that works well for multiple setups. A relevant report can be seen here: https://github.com/datahop/p2p-service-discovery/blob/master/doc/report_m4/reports/waiting_time.md
